src/Geekhub/DreamBundle/Entity/Status.php
<?php

namespace Geekhub\DreamBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * Status
 *
 * @ORM\Table(name="status")
 * @ORM\Entity(repositoryClass="Geekhub\DreamBundle\Repository\CommonRepository")
 */
class Status implements EventInterface
{
    const SUBMITTED            = 'submitted';
    const REJECTED             = 'rejected';
    const COLLECTING_RESOURCES = 'collecting-resources';
    const IMPLEMENTING         = 'implementing';
    const COMPLETED            = 'completed';
    const SUCCESS              = 'success';
    const FAIL                 = 'fail';

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     * @return string
     *
     * @ORM\Column(name="title", type="string", length=30)
     */
    protected $title;

    /**
     * @var \DateTime
     *
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(name="createdAt", type="datetime")
     */
    protected $createdAt;

    /**
     *
     * @ORM\ManyToOne(targetEntity="Dream", inversedBy="statuses")
     */
    protected $dream;

    public function __construct($title)
    {
        $this->title = $title;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param  string $title
     * @return Status
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set createdAt
     *
     * @param  \DateTime $createdAt
     * @return Status
     */
    public function setCreatedAt($createdAt)
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Get createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->createdAt;
    }

    /**
     * Set dream
     *
     * @param  \Geekhub\DreamBundle\Entity\Dream $dream
     * @return Status
     */
    public function setDream(\Geekhub\DreamBundle\Entity\Dream $dream = null)
    {
        $this->dream = $dream;

        return $this;
    }

    /**
     * Get dream
     *
     * @return \Geekhub\DreamBundle\Entity\Dream
     */
    public function getDream()
    {
        return $this->dream;
    }

    public static function getStatusesArray()
    {
        return array(
            self::SUBMITTED => self::SUBMITTED,
            self::COLLECTING_RESOURCES => self::COLLECTING_RESOURCES,
            self::REJECTED => self::REJECTED,
            self::IMPLEMENTING => self::IMPLEMENTING,
            self::COMPLETED => self::COMPLETED,
            self::SUCCESS => self::SUCCESS,
            self::FAIL => self::FAIL,
        );
    }

    public function getEventImage()
    {
        return $this->getDream()->getMediaPoster();
    }

    public function getEventTitle()
    {
        return sprintf('Dream "%s", has changed status to "%s"', $this->getDream()->getTitle(), $this->getTitle());
    }
}

src/Geekhub/DreamBundle/Resources/views/Block/block_dream_activity.html.twig
{% extends sonata_block.templates.block_base %}
{% block block %}
    <ul class='timeline'>
        {% for day, events in sortedEvents %}
            <li class="year">{{ day|format('Y m d') }}</li>
            {% for event in events %}
                <li class='event{% if loop.first %} offset-first{% endif %}'>
                    <img src="{{ event.eventImage|mediaPath|imagine_filter('dream_preview_in_menu') }}" style="float: left">
                    <time datetime="{{ event.createdAt|date('Y-m-dTH:i') }}">{{ event.createdAt|date('H:i') }}</time>
                    {{ event.eventTitle }}
                </li>
            {% endfor %}
        {% endfor %}
    </ul>
        {#<li class='event offset-first'>#}
            {#Something amazing happened today, but it's a secret#}
        {#</li>#}
        {#<li class='event' href="#">#}
            {#Timeline.css is <b>dynamic</b>, <b>responsive</b> and optimized to <b>demonstrate events</b> in your life in a <b>simple and clear</b> way#}
        {#</li>#}
        {#<li class="event">#}
            {#<a href="http://christian-fei.com" title="christian fei">#}
                {#made with &lt;3 by <img class='no-box centered' src="https://s3-eu-west-1.amazonaws.com/cf.img/var/face.svg" alt="christian fei">#}
            {#</a>#}
        {#</li>#}
        {#<li class="event">#}
            {#<a href="http://codepen.io/christian-fei/pen/BJily">#}
                {#Open source project on codepen.io#}
                {#<img class='no-box centered' src="http://davidwalsh.name/demo/codepenLogo.png" alt="">#}
            {#</a>#}
        {#</li>#}
        {#<li class='event'>#}
            {#Look, a sleepy kitten: <br/>#}
            {#<img class='no-box' src="http://ih2.redbubble.net/image.10311838.0354/flat,550x550,075,f.jpg"/>#}
            {#<a href='http://ih2.redbubble.net/image.10311838.0354/flat,550x550,075,f.jpg'>&copy;</a>#}
        {#</li>#}
        {#<li class="year">2012</li>#}
        {#<li class="event offset-first">#}
            {#<p>To infinity  ... </p>#}
            {#<img class='centered no-box' src="http://upload.wikimedia.org/wikipedia/en/7/75/Buzz-lightyear-toy-story-3-wallpaper.jpg" alt="">#}
            {#<a href='http://upload.wikimedia.org/wikipedia/en/7/75/Buzz-lightyear-toy-story-3-wallpaper.jpg'>&copy;</a>#}
        {#</li>#}
        {#<li class="event">#}
            {#<p>... and beyond!</p>#}
            {#<img class='centered no-box' src="http://brandstyle.com.br/wp-content/uploads/2012/05/Woody-7.jpg" alt="">#}
            {#<a href='http://brandstyle.com.br/wp-content/uploads/2012/05/Woody-7.jpg'>&copy;</a>#}
        {#</li>#}

{% endblock %}